### ISSUE TITLE
Editor window size content overflows 

### ISSUE THREAD

**Issue by RohanPunjani** [helmerapp/micro#72]
After capturing the GIF, when opening the editor window, the size is not compatible with the content, and the content is  overflowed.

![GIF 2024-05-03 at 10-23-13 PM](https://github.com/helmerapp/micro/assets/48467821/7eb19eba-0645-4943-b9c8-a1904ff2ad72)

There is a white background by default for anything that is visible outside of bounds of the window

**Comment by Pranav2612000** [comment]
@clearlysid Were you able to reproduce this? Or is it a windows only issue?

**Comment by clearlysid** [comment]
Seems like a windows-only issue. I can't create it on macOS. I'm pretty sure it has to do with the PhysicalPosition and LogicalPosition being differently handled on both platforms.

**Comment by RohanPunjani** [comment]
The height of the editor window is taken by calculating the preview height + tools height. Preview height is the height that was initially received from the encoder while encoding, but the preview video that was been sent is of always of dimension 3840x2160px 

Normal 600x400 frame:
![image](https://github.com/helmerapp/micro/assets/48467821/fcdf2aae-2911-4230-a43f-9ab67de3fc34)

Normal 400x600 frame:
![image](https://github.com/helmerapp/micro/assets/48467821/5309130e-34a8-4657-b2c5-c6b13907534e)

Normal 800x200 frame:
![image](https://github.com/helmerapp/micro/assets/48467821/a1dd83ed-ec5e-46bc-abea-bc8c495c70b0)

**Comment by RohanPunjani** [comment]
A fix for this is to set aspect ratio always as 3840/2160 for windows


    let mut aspect_ratio = width as f32 / height as f32;
    
    #[cfg(target_os = "windows")]
    {
        aspect_ratio = 3840.00 / 2160.00;
    }

    let preview_height_adjusted = EDITOR_WIDTH as f32 / aspect_ratio;
    let editor_win_height = preview_height_adjusted + TOOLS_HEIGHT as f32;

**Comment by RohanPunjani** [comment]
This is how it looks like now:

| 800 x 200 | 400 x 600 | 600 x 400 |
| -----------|------------|------------|
| ![image](https://github.com/helmerapp/micro/assets/48467821/4eca2f7e-5358-4ea9-a088-c4c180550f86) | ![image](https://github.com/helmerapp/micro/assets/48467821/1f6a3729-a369-4227-8a00-8e5dc91c94fa) | ![image](https://github.com/helmerapp/micro/assets/48467821/3a3a6c15-0473-4631-8ce8-5d96b0025907) |


The issue was with [windows-capture](https://github.com/NiiightmareXD/windows-capture) where the encoded video was not with proper frame dimensions, it has been fixed and also been [merged](https://github.com/NiiightmareXD/windows-capture/pull/56) now which gives the above result.
