### ISSUE TITLE
Export button out of screen if the selected gif area is long

### ISSUE THREAD

**Issue by rajatkulkarni95** [helmerapp/micro#73]
<img width="1470" alt="Screenshot 2024-05-03 at 22 55 45" src="https://github.com/helmerapp/micro/assets/57321156/8267a987-072c-4d8d-b290-b76b4a220e2d">

Device: Mac M2 14'

If you select a long enough area to capture, the export button goes out of bounds

**Comment by Pranav2612000** [comment]
Thank you for pointing it out. We've already fixed the issue and it should be resolved in the next release.
