### ISSUE TITLE
You can time your esc keypress into dismissing the crop window and bugging the app out

### ISSUE THREAD

**Issue by amit-chaudhari1** [helmerapp/micro#82]
## Description
You can time your esc keypress into dismissing the crop window and bugging the app out and having the record button on.
and end up on a  state that you can see the record button but not have the crop area (the position capture is successful there but we've dismissed the window, removing the visual indication for the area that we're going to capture)

![image](https://github.com/helmerapp/micro/assets/21289530/3858f3da-582f-43af-9936-f2c61e75ecda)

## Reproducible steps

press `CtrlorCmdShift2` and then press `Esc` at the right time.
You have to press `Esc` at the right time.
timing the frame creation after doing `mouse_up` at the end of the drag.

## Possible Solution
we are hiding windows from the JS side we should be handling them from the rust side

**Comment by clearlysid** [comment]
Solved with #79 by moving Cropper/Record window hiding logic to the rust side.
